# -*- mode: ruby -*-
# vi: set ft=ruby :

# CentOS Vagrantfile for ARM-based MacBook Pro using QEMU provider
# Using CentOS 7 ARM64 box (CentOS 8+ has been discontinued)

Vagrant.configure("2") do |config|
  # Use CentOS 7 ARM64 box - one of the few ARM64 CentOS boxes available
  # This box was specifically tested with Apple Silicon/M1
  config.vm.box = "ppggff/centos-7-aarch64-2009-4K"

  # Disable automatic box update checking
  config.vm.box_check_update = false

  # Configure the QEMU provider
  config.vm.provider "qemu" do |qe|
    # Use ARM64 architecture (native to Apple Silicon)
    qe.arch = "aarch64"

    # Use the virt machine type optimized for ARM64 with HVF acceleration
    qe.machine = "virt,accel=hvf,highmem=off"

    # Use Cortex-A72 CPU (compatible ARM64 processor)
    qe.cpu = "cortex-a72"

    # Configure memory
    qe.memory = "2G"

    # Configure CPU cores
    qe.smp = "cpus=2,sockets=1,cores=2,threads=1"

    # Use virtio network device for better performance
    qe.net_device = "virtio-net-pci"

    # SSH port configuration
    qe.ssh_port = "50024"

    # Enable SSH port auto-correction if port conflicts occur
    qe.ssh_auto_correct = true
  end

  # Disable default /vagrant synced folder since it can be problematic with QEMU
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Optional: Basic system update and package installation
  # config.vm.provision "shell", inline: <<-SHELL
  #   yum update -y
  #   yum install -y curl wget git vim htop epel-release
  # SHELL
end
